### ISSUE TITLE
Error: failed to meet quorum 

### ISSUE THREAD

**Issue by cnspot** [olegmitrakhovich/Defi-Arb-Bot#3]
I can run this bot, but some erro happen,
I have no idea about it.
 
Kyber -> Uniswap. Dai input / output: 20000 / 19867.970249227993481323
Uniswap -> Kyber. Dai input / output: 20000 / 19888.434829561962045591
New block received. Block # 10772418
Warning: 0x6b175474e89094c44da98b954eedeac495271d0f is not checksummed.
updateEthPrice ing ：0x6b175474e89094c44da98b954eedeac495271d0f
updateEthPrice end ：0x6b175474e89094c44da98b954eedeac495271d0f
(node:6956) UnhandledPromiseRejectionWarning: Error: failed to meet quorum (method="call", params={"transaction":{"to":"0xA478c2975Ab1Ea89e8196811F51A7B7Ade33eB11","data":"0x0902f1ac"},"blockTag":"latest"}, results=[{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":-1024,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":0,"baseUrl":"https://api.etherscan.io","apiKey":"9D13ZE7XSBTJ94N9BNJ2MA33VMAY2YPIRB","_internalBlockNumber":{}},"weight":1,"start":1598925148680,"error":{"reason":"missing response","code":"SERVER_ERROR","requestBody":null,"requestMethod":"GET","serverError":{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"75.126.2.43","port":443},"url":"https://api.etherscan.io/api?module=proxy&action=eth_call&to=0xa478c2975ab1ea89e8196811f51a7b7ade33eb11&data=0x0902f1ac&apikey=9D13ZE7XSBTJ94N9BNJ2MA33VMAY2YPIRB"}},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":10767750,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1598925147726,"connection":{"url":"https://cloudflare-eth.com/"},"_nextId":44,"_internalBlockNumber":{},"_fastBlockNumber":10767750,"_fastBlockNumberPromise":{}},"weight":1,"start":1598925148680,"result":"0x0000000000000000000000000000000000000000002322989de30ee203751b3d00000000000000000000000000000000000000000000156d04917f45cba89d6b000000000000000000000000000000000000000000000000000000005f4c6bed"},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":10772416,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1598925148679,"connection":{"url":"https://eth-mainnet.alchemyapi.io/v2/_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC"},"_nextId":44,"apiKey":"_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC","_internalBlockNumber":{},"_fastBlockNumber":10772416,"_fastBlockNumberPromise":{}},"weight":1,"start":1598925169682,"result":"0x0000000000000000000000000000000000000000003584c7d99b3f6304be89d2000000000000000000000000000000000000000000001ff4d99c04d1751f9e25000000000000000000000000000000000000000000000000000000005f4da953"},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":10772416,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1598925147851,"connection":{"url":"https://mainnet.infura.io/v3/84842078b09946638c03157f83405213"},"_nextId":44,"apiKey":"84842078b09946638c03157f83405213","projectId":"84842078b09946638c03157f83405213","projectSecret":null,"_internalBlockNumber":{},"_fastBlockNumber":10772416,"_fastBlockNumberPromise":{}},"weight":1,"start":1598925169682,"result":"0x00000000000000000000000000000000000000000035878cb4ca1d8481b71005000000000000000000000000000000000000000000001ff333b3490718e4b76e000000000000000000000000000000000000000000000000000000005f4da95a"}], provider={"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":10772416,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1598925148679,"providerConfigs":[{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":10772416,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1598925147851,"connection":{"url":"https://mainnet.infura.io/v3/84842078b09946638c03157f83405213"},"_nextId":44,"apiKey":"84842078b09946638c03157f83405213","projectId":"84842078b09946638c03157f83405213","projectSecret":null,"_internalBlockNumber":{},"_fastBlockNumber":10772416,"_fastBlockNumberPromise":{}},"weight":1,"stallTimeout":750,"priority":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":-1024,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":0,"baseUrl":"https://api.etherscan.io","apiKey":"9D13ZE7XSBTJ94N9BNJ2MA33VMAY2YPIRB","_internalBlockNumber":{}},"weight":1,"stallTimeout":750,"priority":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":10772416,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1598925148679,"connection":{"url":"https://eth-mainnet.alchemyapi.io/v2/_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC"},"_nextId":44,"apiKey":"_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC","_internalBlockNumber":{},"_fastBlockNumber":10772416,"_fastBlockNumberPromise":{}},"weight":1,"stallTimeout":750,"priority":1},{"provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"_maxInternalBlockNumber":10767750,"_lastBlockNumber":-2,"_pollingInterval":4000,"_fastQueryDate":1598925147726,"connection":{"url":"https://cloudflare-eth.com/"},"_nextId":44,"_internalBlockNumber":{},"_fastBlockNumber":10767750,"_fastBlockNumberPromise":{}},"weight":1,"stallTimeout":750,"priority":1}],"quorum":2,"_highestBlockNumber":10772416,"_internalBlockNumber":{},"_fastBlockNumber":10772416,"_fastBlockNumberPromise":{}}, code=SERVER_ERROR, version=providers/5.0.5)
    at Logger.makeError (C:\Users\Administrator\Downloads\Defi-Arb-Bot-master\node_modules\@ethersproject\logger\lib\index.js:179:21)
    at Logger.throwError (C:\Users\Administrator\Downloads\Defi-Arb-Bot-master\node_modules\@ethersproject\logger\lib\index.js:188:20)
    at FallbackProvider.<anonymous> (C:\Users\Administrator\Downloads\Defi-Arb-Bot-master\node_modules\@ethersproject\providers\lib\fallback-provider.js:626:54)
    at step (C:\Users\Administrator\Downloads\Defi-Arb-Bot-master\node_modules\@ethersproject\providers\lib\fallback-provider.js:46:23)
    at Object.next (C:\Users\Administrator\Downloads\Defi-Arb-Bot-master\node_modules\@ethersproject\providers\lib\fallback-provider.js:27:53)
    at fulfilled (C:\Users\Administrator\Downloads\Defi-Arb-Bot-master\node_modules\@ethersproject\providers\lib\fallback-provider.js:18:58)
(node:6956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by olegmitrakhovich** [comment]
yes I am getting this error too. Something to do with the ethers library, been asking around but nobody has a solution. Let me know if you find anything. The bot will still find ARBs and attempts to do a transaction, which fail most of the time. This is still a work in progress.

**Comment by olegmitrakhovich** [comment]
checkout issue #4

**Comment by cnspot** [comment]
@olegmitrakhovich   thank u very much.
I have another question:  where can I seting  my Eth wallet address？  
I‘m running this bot with your  org vesion code，it seeing to make arbs on you wallet address, I dont know how to change to my wallet address.

way of  set  private_key on .env  file is enough?

**Comment by olegmitrakhovich** [comment]
yes setting your private key in the .env file is enough...however, make sure you deploy your smart contract with the same private key. @cnspot

**Comment by cnspot** [comment]
@olegmitrakhovich  thank u.

**Comment by aluhme** [comment]
> yes setting your private key in the .env file is enough...however, make sure you deploy your smart contract with the same private key. @cnspot

hi @cnspot great job, can you tell me how to deploy the smart contract with the same private key? Did you mean we have to manually deploy the contracts folder .sol using the same wallet address specified or your bot does it automatically?

**Comment by olegmitrakhovich** [comment]
you have to use "truffle migrate --network mainnet --reset" command to deploy your contracts.
